### ISSUE TITLE
[User Story] As a user, I want to be able to login

### ISSUE THREAD

**Issue by ItsMasonn** [Access-Point-Program/cohort-3-authentication-proxy#12]
GIVEN a user enters their username and password
WHEN the user clicks on the 'Sign In' button
THEN the user is taken to the dashboard

### Acceptance Criteria
- [x] There must be a username text field
- [x] There must be a password text field (appears as dots)
- [x] There should be a "Sign In" button that redirects to the dashboard

### Developer Stories
- #48 
- #49   
- #50  
- #51  
- #52

**Comment by chris-marfia** [comment]
https://www.toptal.com/spring/spring-security-tutorial
https://www.bezkoder.com/spring-boot-security-postgresql-jwt-authentication/
https://www.baeldung.com/spring-rest-with-zuul-proxy
