### ISSUE TITLE
As a developer, I need to document our definition of done as a Pull Request template

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-authentication-proxy#18]
As a team, we need to document our definition of done as a markdown template to pre-populate our Pull Requests

### Resources
- [How to create a Pull Request Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [Examples](https://axolo.co/blog/p/part-3-github-pull-request-template)

### Acceptance Criteria
- [x] The DOD is on the Pull Request Template for the team to use

**Comment by chris-marfia** [comment]
@Access-Point-Program/pro-to-type I am moving this story back into Ready. I recommend that you move the file that was created into a `.github` folder as recommended. 

The reason for this will be organizational and we might be adding new things there in the future.

**Comment by ItsMasonn** [comment]
@chris-marfia Resolved.
