### ISSUE TITLE
As a developer, I need to document our definition of ready as an Issue template

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-authentication-proxy#19]
As a team, we need to document our definition of done as a markdown template to pre-populate our Pull Requests

### Resources
- [How to create an Issue Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)
- [Examples](https://github.com/stevemao/github-issue-templates/tree/master)

### Acceptance Criteria
- [x] The Definition of Ready is documented into an Issue template that can be used.

**Comment by ItsMasonn** [comment]
@chris-marfia Resolved.
