### ISSUE TITLE
As a developer, I need an initialized Spring Boot Application

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-authentication-proxy#21]
We need to have a starter project created for a Spring Boot application.

### Resources
- [Spring Initializer](https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.1.3&packaging=jar&jvmVersion=20&groupId=com.access-point&artifactId=proxy&name=proxy&description=Demo%20project%20for%20Spring%20Boot&packageName=com.access-point.proxy&dependencies=web,data-jpa,postgresql,docker-compose,data-rest,security)

### Acceptance Criteria
- [x] When there is an initialized spring boot application in our GitHub repo that everyone on the team can run.

**Comment by ItsMasonn** [comment]
Complete
