### ISSUE TITLE
SPIKE: As a developer, I need to learn how to have an Angular application inside of a Spring Boot application

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-authentication-proxy#22]
We need to research to have an Angular application hosted by the Spring Boot API.

### Hint
- Check out the spring guides on the website

### Acceptance Criteria
- [x] Documented artifacts on how to put and host an Angular application within a spring application
- [x] Documenting our findings in the Google Site

**Comment by ItsMasonn** [comment]
Complete
