### ISSUE TITLE
SPIKE: As a team, we need to learn how to create a Spring Boot application

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-authentication-proxy#23]
As a team, you will meet with your instructor and learn the basics of Spring Boot applications and terminology. Throughout the Sprint you will need to complete the Getting Start with Spring Guide.

### Resources
- [Getting Started with Spring Tutorial](https://spring.io/guides/tutorials/rest/)

### Acceptance Criteria 
- [x] Every member of the team completes the Spring Tutorial.
- [x] Every member of the team submits their code as a pull request to the provided GitHub Repository for Spring tutorials
  - This will be provided during the first lecture on Spring Boot

**Comment by ItsMasonn** [comment]
Complete
